In [ ]:
import pandas as pd
import nltk 


In [ ]:
df= pd.read_csv('/content/train.csv')


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
# droping NAN values
df = df.dropna()

In [ ]:
## getting independent feature
X = df.drop('label',axis=1)


In [ ]:
y = df['label']

In [ ]:
import tensorflow as tf

In [ ]:
y.shape

(18285,)

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size = 5000

<h1> One_hot_representation </h1>


In [ ]:
messages = X.copy()


In [ ]:
messages.reset_index(inplace = True)

In [ ]:
import nltk 
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer


In [ ]:
nltk.download('stopwords')
nltk.download()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all


       | 
       | Downloading package abc to /root/nltk_data...
       |   Unzipping corpora/abc.zip.
       | Downloading package alpino to /root/nltk_data...
       |   Unzipping corpora/alpino.zip.
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger.zip.
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Unzipping taggers/averaged_perceptron_tagger_ru.zip.
       | Downloading package basque_grammars to /root/nltk_data...
       |   Unzipping grammars/basque_grammars.zip.
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Unzipping corpora/biocreative_ppi.zip.
       | Downloading package bllip_wsj_no_aux to /root/nltk_data...
       |   Unzipping models/bllip_wsj_no_aux.zip.
       | Downloading package book_grammars to /root/nltk_data...
       |   Unzipping grammars/book_grammars.zip.
       | Downloading 


---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [ ]:
### Dataset Preprocessing
ps = PorterStemmer()
lm = WordNetLemmatizer()
corpus = []
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]'," ",messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [lm.lemmatize(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
one_hot_rep =[one_hot(words,voc_size) for words in corpus]
one_hot_rep

[[2672, 1454, 3813, 3843, 312, 415, 4937, 2390, 1000, 1395],
 [4989, 3627, 961, 1805, 2343, 247, 4114],
 [2760, 3272, 2989, 4655],
 [1395, 2409, 3917, 494, 4725, 3532],
 [2212, 2343, 981, 4049, 2778, 3733, 2343, 2749, 3165, 1621],
 [2909,
  4737,
  3162,
  663,
  105,
  1540,
  45,
  4423,
  916,
  2142,
  4848,
  1795,
  3260,
  4865,
  4114],
 [3836, 2458, 1656, 1201, 3732, 2044, 1825, 4853, 1874, 3104, 2214],
 [3892, 3751, 2729, 3199, 3457, 2158, 1540, 2063, 1874, 3104, 2214],
 [4061, 3590, 4024, 2181, 3134, 4316, 92, 2032, 1540, 3506],
 [2496, 1752, 4396, 2568, 4426, 3893, 4097, 2900],
 [3230, 3071, 2768, 2611, 415, 955, 1305, 1699, 560, 324, 4559],
 [494, 4918, 312, 297, 1540, 3457],
 [3794, 447, 2587, 2819, 1635, 4781, 1145, 2701, 3735],
 [2124, 3044, 1978, 1407, 3999, 3473, 1580, 1874, 3104, 2214],
 [3177, 4157, 4151, 4012, 4973, 1874, 3104, 2214],
 [509, 2607, 2245, 2175, 3995, 748, 1276, 2987, 3886, 234],
 [22, 383, 3627],
 [2423, 4331, 2386, 2148, 1540, 29, 693, 4114],
 [48, 

<h1> Embedding Representation<h1>

In [ ]:
sent_length = 20
embedded_docs = pad_sequences(one_hot_rep,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2390 1000 1395]
 [   0    0    0 ... 2343  247 4114]
 [   0    0    0 ... 3272 2989 4655]
 ...
 [   0    0    0 ... 1874 3104 2214]
 [   0    0    0 ... 1684 4015  273]
 [   0    0    0 ... 4911 2121 1941]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2672,
       1454, 3813, 3843,  312,  415, 4937, 2390, 1000, 1395], dtype=int32)

In [ ]:
## creating model
embedding_vector_features = 50
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 50)            250000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 310,501
Trainable params: 310,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.3,random_state=42)

In [ ]:
## Model training
model.fit(X_train,y_train,validation_data =(X_test,y_test),epochs=20,batch_size=64)

Epoch 1/20
200/200 [==============================] - 11s 42ms/step - loss: 0.3126 - accuracy: 0.8524 - val_loss: 0.1960 - val_accuracy: 0.9145
Epoch 2/20
200/200 [==============================] - 8s 39ms/step - loss: 0.1311 - accuracy: 0.9494 - val_loss: 0.2000 - val_accuracy: 0.9174
Epoch 3/20
200/200 [==============================] - 8s 38ms/step - loss: 0.0897 - accuracy: 0.9675 - val_loss: 0.2366 - val_accuracy: 0.9152
Epoch 4/20
200/200 [==============================] - 8s 38ms/step - loss: 0.0606 - accuracy: 0.9784 - val_loss: 0.2636 - val_accuracy: 0.9081
Epoch 5/20
200/200 [==============================] - 8s 38ms/step - loss: 0.0477 - accuracy: 0.9847 - val_loss: 0.3195 - val_accuracy: 0.9098
Epoch 6/20
200/200 [==============================] - 8s 39ms/step - loss: 0.0309 - accuracy: 0.9902 - val_loss: 0.4142 - val_accuracy: 0.9025
Epoch 7/20
200/200 [==============================] - 8s 38ms/step - loss: 0.0219 - accuracy: 0.9932 - val_loss: 0.4863 - val_accuracy: 0.909

<h1> Performance Metrics and Accuracy
</h1>

In [ ]:
y_pred = model.predict(X_test)
prediction_result = []
for i in y_pred:
  if i[0] < 0.5:
    prediction_result.append(0)
  else:
    prediction_result.append(1)

[1 0 0 ... 1 0 1]


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,prediction_result)

array([[2782,  325],
       [ 199, 2180]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction_result)

0.9044841414509661